/* Divinity: Original Sin 2 — Definitive Edition crafting data
 * Source: Mellarius' "Complete crafting tables (700+ positions)" Steam guide.
 * mod flags:  null = base game,  "crafters_kit" = (*) Crafter's Kit mod,  "herb_garden" = (**) Herb Gardens mod
 * Each recipe: { result, ingredients:[...], category, mod, effect? }
 */
window.RECIPES = [
  // ----------------------- CONTAINER -----------------------
  { result: "Backpack", ingredients: ["Leather Scraps", "Rope"], category: "Container" },

  // ----------------------- FURNITURE -----------------------
  { result: "Boiling Pot", ingredients: ["Cooking Pot", "Campfire"], category: "Furniture" },
  { result: "Bucket of Water", ingredients: ["Bucket", "Water Barrel"], category: "Furniture" },
  { result: "Oil Barrel", ingredients: ["Empty Barrel", "(Fixed) Oil Pump"], category: "Furniture" },
  { result: "Barrel", ingredients: ["Crafter's Kit", "Wood", "Nails"], category: "Furniture", mod: "crafters_kit" },
  { result: "Oil Barrel", ingredients: ["Crafter's Kit", "Wood", "a source of oil"], category: "Furniture", mod: "crafters_kit" },
  { result: "Water Barrel", ingredients: ["Crafter's Kit", "Wood", "a source of water"], category: "Furniture", mod: "crafters_kit" },
  { result: "Ooze Barrel", ingredients: ["Crafter's Kit", "Wood", "a source of poison"], category: "Furniture", mod: "crafters_kit" },
  { result: "Cursed Oil Barrel", ingredients: ["Oil Barrel", "Tormented Soul"], category: "Furniture", mod: "crafters_kit" },
  { result: "Cursed Oil Barrel", ingredients: ["Oil Barrel", "High Quality Tormented Soul"], category: "Furniture", mod: "crafters_kit" },
  { result: "Cursed Oil Barrel", ingredients: ["Oil Barrel", "Alien Tormented Soul"], category: "Furniture", mod: "crafters_kit" },
  { result: "Blessed Water Barrel", ingredients: ["Water Barrel", "Life Essence"], category: "Furniture", mod: "crafters_kit" },
  { result: "Blessed Water Barrel", ingredients: ["Water Barrel", "High Quality Life Essence"], category: "Furniture", mod: "crafters_kit" },
  { result: "Blessed Water Barrel", ingredients: ["Water Barrel", "Alien Life Essence"], category: "Furniture", mod: "crafters_kit" },

  // ----------------------- ITEMS -----------------------
  { result: "Bonedust", ingredients: ["Bone/Skull", "Mortar and Pestle"], category: "Items" },
  { result: "Bonedust", ingredients: ["Chew Toy", "Mortar and Pestle"], category: "Items" },
  { result: "Stardust", ingredients: ["Stardust Herb", "Mortar and Pestle"], category: "Items" },
  { result: "Pouch of Superior Stardust", ingredients: ["Superior Stardust Herb", "Mortar and Pestle"], category: "Items" },
  { result: "Pixie Dust", ingredients: ["Bonedust", "Stardust"], category: "Items" },
  { result: "Pouch of Superior Pixie Dust", ingredients: ["Bonedust", "Pouch of Superior Stardust"], category: "Items" },
  { result: "Empty Bottle", ingredients: ["Broken Bottle", "Hammer"], category: "Items" },
  { result: "Bucket with Water", ingredients: ["Bucket", "Water Barrel"], category: "Items" },
  { result: "Cloth Scraps", ingredients: ["Bed Linen", "Cutting Tool"], category: "Items" },
  { result: "Repair Hammer", ingredients: ["Crafter's Kit", "Metal Scraps", "Wood Chips"], category: "Items", mod: "crafters_kit" },
  { result: "Pillow", ingredients: ["Feather", "Cutting Tool"], category: "Items" },
  { result: "Improvised Shovel", ingredients: ["Long Branch", "Bowl"], category: "Items" },
  { result: "Lockpicks", ingredients: ["Hammer", "Nails"], category: "Items" },
  { result: "Lockpicks", ingredients: ["Soap", "Key"], category: "Items" },
  { result: "Lockpicks", ingredients: ["Needle", "Needle"], category: "Items" },
  { result: "Lockpicks", ingredients: ["Crafter's Kit", "any metal"], category: "Items", mod: "crafters_kit" },
  { result: "Nails", ingredients: ["Scale Scraps", "Pincers"], category: "Items", mod: "crafters_kit" },
  { result: "Quill", ingredients: ["Feather", "Cutting Tool"], category: "Items", mod: "crafters_kit" },
  { result: "Rope", ingredients: ["Yarn", "Yarn"], category: "Items" },
  { result: "Sheet of Paper", ingredients: ["Wood Pulp", "Oven"], category: "Items" },
  { result: "Sheet of Paper", ingredients: ["Water", "Leather Scraps"], category: "Items", mod: "crafters_kit" },
  { result: "Trap Disarm Toolkit", ingredients: ["Tongs", "a sharp piece of metal"], category: "Items" },
  { result: "Trap Mechanism", ingredients: ["Crafter's Kit", "Fuse", "Metal Scraps"], category: "Items", mod: "crafters_kit" },
  { result: "Undeployed Firestorm Trap", ingredients: ["Firestorm Grenade", "Trap Mechanism"], category: "Items", mod: "crafters_kit" },
  { result: "Thunderbolt Trap", ingredients: ["Taser Grenade", "Trap Mechanism"], category: "Items", mod: "crafters_kit" },
  { result: "Smoke Trap", ingredients: ["Smoke Grenade", "Trap Mechanism"], category: "Items", mod: "crafters_kit" },
  { result: "Undeployed Dazzler Trap", ingredients: ["Flashbang Grenade", "Trap Mechanism"], category: "Items", mod: "crafters_kit" },
  { result: "Poison Gas Trap", ingredients: ["Poison Cloud Grenade", "Trap Mechanism"], category: "Items", mod: "crafters_kit" },
  { result: "Undeployed Nailbomb Trap", ingredients: ["Nailbomb Grenade", "Trap Mechanism"], category: "Items", mod: "crafters_kit" },
  { result: "Undeployed Displacer Trap", ingredients: ["Teleportation Scroll", "Trap Mechanism"], category: "Items", mod: "crafters_kit" },
  { result: "Empty Canister", ingredients: ["Crafter's Kit", "Metal Scraps", "Metal Scraps"], category: "Items", mod: "crafters_kit" },
  { result: "Short Stick", ingredients: ["Wood Chips and Arrow Shaft", "Bench Saw"], category: "Items" },
  { result: "Log", ingredients: ["Wood Chips and Long Branch", "Bench Saw"], category: "Items" },
  { result: "Log", ingredients: ["Wood Chips and Long Branch", "Cutting Tool"], category: "Items" },
  { result: "Long Branch", ingredients: ["Wood Chips and Short Stick", "Bench Saw"], category: "Items" },
  { result: "Wood Pulp", ingredients: ["Wood Chips", "Water"], category: "Items" },
  { result: "Wool", ingredients: ["Shears", "Sheep + Pet Pal skill"], category: "Items" },
  { result: "Yarn", ingredients: ["Wool", "Wool"], category: "Items" },

  // ----------------------- ARMOUR -----------------------
  { result: "Thread", ingredients: ["Hair", "(Well)"], category: "Armour" },
  { result: "Thread", ingredients: ["Hair", "Hair"], category: "Armour" },
  { result: "Needle and Thread", ingredients: ["Needle", "Thread"], category: "Armour" },
  { result: "Cloth Scraps", ingredients: ["Bed Linen", "Cutting Tool"], category: "Armour" },
  { result: "Leather Scraps", ingredients: ["Cutting Tool", "Animal Hide"], category: "Armour" },
  { result: "Leather Scraps", ingredients: ["Dagger", "Animal Hide"], category: "Armour" },
  { result: "Leather Scraps", ingredients: ["Knife", "Animal Hide"], category: "Armour" },
  { result: "Handmade Shield", ingredients: ["Metal Scraps", "Wood Chips"], category: "Armour" },
  { result: "Handmade Chain Armour", ingredients: ["Needle and Thread", "Metal Scraps"], category: "Armour" },
  { result: "Handmade Cloth Shirt", ingredients: ["Needle and Thread", "Cloth Scraps"], category: "Armour" },
  { result: "Handmade Leather Armour", ingredients: ["Needle and Thread", "Leather Scraps"], category: "Armour" },
  { result: "Handmade Mage Armour", ingredients: ["Needle and Thread", "Cloth Scraps", "Pixie Dust"], category: "Armour" },
  { result: "Handmade Plate Armour", ingredients: ["Plate Scraps", "(Anvil)"], category: "Armour" },
  { result: "Handmade Plate Armour", ingredients: ["Plate Scraps", "Hammer", "(Anvil)"], category: "Armour" },
  { result: "Handmade Scale Armour", ingredients: ["Scale Scraps", "Hammer", "(Anvil)"], category: "Armour" },
  { result: "Dwarven Mask of the Shapeshifter", ingredients: ["BodyPart Face Dwarf", "Source Orb"], category: "Armour" },
  { result: "Elven Mask of the Shapeshifter", ingredients: ["BodyPart Face Elf", "Source Orb"], category: "Armour" },
  { result: "Human Mask of the Shapeshifter", ingredients: ["BodyPart Face Human", "Source Orb"], category: "Armour" },
  { result: "Lizard Mask of the Shapeshifter", ingredients: ["BodyPart Face Lizard", "Source Orb"], category: "Armour" },
  { result: "Armour of Eternals", ingredients: ["Eternal Artefact", "Eternal Plate", "Metal Scraps", "Source Orb"], category: "Armour" },

  // ----------------------- ARMOUR - buff/boost/upgrade -----------------------
  { result: "+XX% elemental resistance / +XX% max physical armour", ingredients: ["any armor with empty rune socket", "Small/Medium/Large/Giant Rune"], category: "Armour Upgrade" },
  { result: "+XX% elem. resist & +X combat ability/Constitution", ingredients: ["any armor with empty rune socket", "Mystical Small/Medium/Large/Giant Rune"], category: "Armour Upgrade" },
  { result: "+XX% elem. resist & +X Strength/Finesse/Con/Int/Mem/Wits", ingredients: ["any armor with empty rune socket", "Small/Medium/Large/Giant Rune of Power"], category: "Armour Upgrade" },
  { result: "+XX trinket stat (Dodging/Vitality/Magic armour/Crit/Init/Accuracy)", ingredients: ["any trinket with empty rune socket", "Small/Medium/Large/Giant Rune"], category: "Armour Upgrade" },
  { result: "+XX trinket stat & +X Aero/Mem/Geo/Hydro/Pyro/Necro", ingredients: ["any trinket with empty rune socket", "Mystical Small/Medium/Large/Giant Rune"], category: "Armour Upgrade" },
  { result: "+XX trinket stat & +X Finesse/Strength/Intelligence", ingredients: ["any trinket with empty rune socket", "Small/Medium/Large/Giant Rune of Power"], category: "Armour Upgrade" },
  { result: "Boots (Slipping immunity)", ingredients: ["Nails", "Boots"], category: "Armour Upgrade" },
  { result: "Amulet (Ataraxian)", ingredients: ["Eternal Artefact", "Amulet"], category: "Armour Upgrade" },
  { result: "Belt (Ataraxian)", ingredients: ["Eternal Artefact", "Belt"], category: "Armour Upgrade" },
  { result: "Boots (Ataraxian)", ingredients: ["Eternal Artefact", "Shoes/Boots"], category: "Armour Upgrade" },
  { result: "Gloves (Ataraxian)", ingredients: ["Eternal Artefact", "Gloves"], category: "Armour Upgrade" },
  { result: "Helmet (Ataraxian)", ingredients: ["Eternal Artefact", "Helmet"], category: "Armour Upgrade" },
  { result: "Pants (Ataraxian)", ingredients: ["Eternal Artefact", "Pants"], category: "Armour Upgrade" },
  { result: "Ring (Ataraxian)", ingredients: ["Eternal Artefact", "Ring"], category: "Armour Upgrade" },
  { result: "Upperbody (Ataraxian)", ingredients: ["Eternal Artefact", "Upperbody armor"], category: "Armour Upgrade" },

  // ----------------------- WEAPON -----------------------
  { result: "Sinew", ingredients: ["Rabbit Meat", "Cutting Tool", "Sharp Rock"], category: "Weapon", mod: "crafters_kit" },
  { result: "Sinew", ingredients: ["Rat's Tail", "Rat's Tail", "Cutting Tool"], category: "Weapon", mod: "crafters_kit" },
  { result: "Bowstring", ingredients: ["Sinew", "Sinew"], category: "Weapon" },
  { result: "Bowstring", ingredients: ["Yarn", "Yarn", "Needle"], category: "Weapon", mod: "crafters_kit" },
  { result: "Rope", ingredients: ["Yarn/Wool", "Yarn/Wool"], category: "Weapon" },
  { result: "Cloth Scraps", ingredients: ["Bed Linen", "Cutting Tool"], category: "Weapon" },
  { result: "Big Tongs Roped Together", ingredients: ["Cloth Scraps", "Tongs"], category: "Weapon" },
  { result: "Big Tongs Roped Together", ingredients: ["Leather Scraps", "Tongs"], category: "Weapon" },
  { result: "Crossbow", ingredients: ["Crossbow Without Bowstring", "Bowstring"], category: "Weapon" },
  { result: "Handmade Sword", ingredients: ["Metal Scraps", "Hammer", "(Anvil)"], category: "Weapon" },
  { result: "Improvised Wand", ingredients: ["Short Stick", "Skull Bird"], category: "Weapon" },
  { result: "Improvised Wand", ingredients: ["Short Stick", "Skull Human Ancient"], category: "Weapon" },
  { result: "Improvised Wand", ingredients: ["Short Stick", "Skull Human"], category: "Weapon" },
  { result: "Improvised Staff", ingredients: ["Long Branch", "Shell"], category: "Weapon" },
  { result: "Knife On A Stick", ingredients: ["Short Stick", "Dagger", "Rope"], category: "Weapon" },
  { result: "Knife On A Stick", ingredients: ["Short Stick", "Knife", "Rope"], category: "Weapon" },
  { result: "Makeshift Club", ingredients: ["Long Branch", "Cloth Scraps"], category: "Weapon" },
  { result: "Makeshift Club", ingredients: ["Long Branch", "Leather Scraps"], category: "Weapon" },
  { result: "Sharp Rock", ingredients: ["Sharp Rock", "Sharp Rock"], category: "Weapon" },
  { result: "Primitive Harpoon", ingredients: ["Long Branch", "Arrowhead"], category: "Weapon" },
  { result: "Primitive Harpoon", ingredients: ["Long Branch", "Dagger", "Rope"], category: "Weapon" },
  { result: "Primitive Harpoon", ingredients: ["Long Branch", "Knife", "Rope"], category: "Weapon" },
  { result: "Primitive Harpoon", ingredients: ["Long Branch", "Sharp piece of metal"], category: "Weapon" },
  { result: "Sharp Stone On A Big Branch", ingredients: ["Long Branch", "Piece of Rock"], category: "Weapon" },
  { result: "Sharp Stone On A Stick", ingredients: ["Short Stick", "Piece of Rock"], category: "Weapon" },
  { result: "Shiv", ingredients: ["Sharp piece of metal", "Cloth Scraps"], category: "Weapon" },
  { result: "Shiv", ingredients: ["Sharp piece of metal", "Hammer", "(Anvil)"], category: "Weapon" },
  { result: "Shiv", ingredients: ["Sharp piece of metal", "Handkerchief"], category: "Weapon" },
  { result: "Shiv", ingredients: ["Sharp piece of metal", "Leather Scraps"], category: "Weapon" },
  { result: "Toy Crossbow", ingredients: ["Short Stick", "Long Branch"], category: "Weapon" },
  { result: "Twig With A String", ingredients: ["Short Stick", "Bowstring"], category: "Weapon" },

  // ----------------------- WEAPON - buff/boost/upgrade -----------------------
  { result: "+XX% element damage", ingredients: ["any weapon with empty rune socket", "Small/Medium/Large/Giant Rune"], category: "Weapon Upgrade" },
  { result: "+XX% element damage & +X Combat Ability/Wits", ingredients: ["any weapon with empty rune socket", "Mystical Small/Medium/Large/Giant Rune"], category: "Weapon Upgrade" },
  { result: "+XX% element damage & +X Finesse/Strength/Intelligence", ingredients: ["any weapon with empty rune socket", "Small/Medium/Large/Giant Rune of Power"], category: "Weapon Upgrade" },
  { result: "Poisoned Weapon", ingredients: ["Poison", "Weapon"], category: "Weapon Upgrade" },
  { result: "Fire Enchanted Weapon", ingredients: ["Cooking Station (fire source)", "oil source", "Weapon"], category: "Weapon Upgrade", mod: "crafters_kit" },
  { result: "Buffed Weapon", ingredients: ["Eternal Artefact", "weapon (except wands and staves)"], category: "Weapon Upgrade" },

  // ----------------------- RUNES -----------------------
  { result: "Bonedust", ingredients: ["Bone", "Mortar and Pestle"], category: "Runes" },
  { result: "Bonedust", ingredients: ["Chew Toy", "Mortar and Pestle"], category: "Runes" },
  { result: "Stardust", ingredients: ["Stardust Herb", "Mortar and Pestle"], category: "Runes" },
  { result: "Pixie Dust", ingredients: ["Bonedust", "Stardust"], category: "Runes" },
  { result: "Pouch of Superior Stardust", ingredients: ["Superior Stardust Herb", "Mortar and Pestle"], category: "Runes" },
  { result: "Pouch of Superior Pixie Dust", ingredients: ["Bonedust", "Pouch of Superior Stardust"], category: "Runes" },
  { result: "Giant % Rune", ingredients: ["Pouch of Superior Pixie Dust", "Large % Rune"], category: "Runes" },
  { result: "Large % Rune", ingredients: ["Pixie Dust", "Medium % Rune"], category: "Runes" },
  { result: "Medium % Rune", ingredients: ["Pixie Dust", "Small % Rune"], category: "Runes" },
  { result: "Small Flame Rune", ingredients: ["Wood", "Oil", "Pixie Dust"], category: "Runes" },
  { result: "Small Frost Rune", ingredients: ["Water", "Metal", "Pixie Dust"], category: "Runes" },
  { result: "Small Masterwork Rune", ingredients: ["Log Livewood", "Wine", "Pixie Dust"], category: "Runes" },
  { result: "Small Thunder Rune", ingredients: ["Water", "Gold", "Pixie Dust"], category: "Runes" },
  { result: "Small Rock Rune", ingredients: ["Rock", "Beer", "Pixie Dust"], category: "Runes" },
  { result: "Small Venom Rune", ingredients: ["Bone", "Poison", "Pixie Dust"], category: "Runes" },
  { result: "Giant % Rune of Power", ingredients: ["Giant % Rune", "Rune Frame of Power"], category: "Runes" },
  { result: "Large % Rune of Power", ingredients: ["Large % Rune", "Rune Frame of Power"], category: "Runes" },
  { result: "Medium % Rune of Power", ingredients: ["Medium % Rune", "Rune Frame of Power"], category: "Runes" },
  { result: "Small % Rune of Power", ingredients: ["Small % Rune", "Rune Frame of Power"], category: "Runes" },
  { result: "Mystical Giant % Rune", ingredients: ["Giant % Rune", "Mystical Rune Frame"], category: "Runes" },
  { result: "Mystical Large % Rune", ingredients: ["Large % Rune", "Mystical Rune Frame"], category: "Runes" },
  { result: "Mystical Medium % Rune", ingredients: ["Medium % Rune", "Mystical Rune Frame"], category: "Runes" },
  { result: "Mystical Small % Rune", ingredients: ["Small % Rune", "Mystical Rune Frame"], category: "Runes" },

  // ----------------------- ARROWHEADS and arrowshafts -----------------------
  { result: "Arrow Shaft and Wood Chips", ingredients: ["Axe / Sword / any cutting tool", "Short Stick"], category: "Arrowheads" },
  { result: "Arrowhead and Arrowhead", ingredients: ["Cutting Tool", "Bone"], category: "Arrowheads" },
  { result: "Arrowhead and Arrowhead", ingredients: ["Cutting Tool", "Sharp Piece of Metal"], category: "Arrowheads" },
  { result: "Arrowhead and Arrowhead", ingredients: ["Cutting Tool", "Sharp Rock"], category: "Arrowheads" },
  { result: "Blessed Water Arrowhead", ingredients: ["Source Orb", "Water Arrowhead"], category: "Arrowheads" },
  { result: "Charming Arrowhead", ingredients: ["Honey", "Arrowhead"], category: "Arrowheads" },
  { result: "Cursed Fire Arrowhead", ingredients: ["Source Orb", "Fire Arrowhead"], category: "Arrowheads" },
  { result: "Explosive Arrowhead", ingredients: ["Oil", "Fire Arrowhead"], category: "Arrowheads" },
  { result: "Fire Arrowhead", ingredients: ["Arrowhead", "any Fire Essence"], category: "Arrowheads" },
  { result: "Fire Arrowhead", ingredients: ["Arrowhead", "oven / cooking station / campfire"], category: "Arrowheads", mod: "crafters_kit" },
  { result: "Freezing Arrowhead", ingredients: ["any Water Essence", "Arrowhead"], category: "Arrowheads" },
  { result: "Knockdown Arrowhead", ingredients: ["Cutting Tool", "Antler / Adult Antler"], category: "Arrowheads" },
  { result: "Poisoncloud Arrowhead", ingredients: ["any Earth Essence", "Arrowhead"], category: "Arrowheads" },
  { result: "Poisoned Arrowhead", ingredients: ["Poison", "Arrowhead"], category: "Arrowheads" },
  { result: "Shocking Arrowhead", ingredients: ["any Air Essence", "Arrowhead"], category: "Arrowheads" },
  { result: "Shocking Arrowhead", ingredients: ["Cutting Tool", "Tooth"], category: "Arrowheads" },
  { result: "Short Stick and Wood Chips", ingredients: ["Cutting Tool", "Long Branch"], category: "Arrowheads" },
  { result: "Slowdown Arrowhead", ingredients: ["Oil", "Arrowhead"], category: "Arrowheads" },
  { result: "Steamcloud Arrowhead", ingredients: ["Water", "Fire Arrowhead"], category: "Arrowheads" },
  { result: "Static Cloud Arrowhead", ingredients: ["any source of water", "Shocking Arrowhead"], category: "Arrowheads" },
  { result: "Static Cloud Arrowhead", ingredients: ["any air essence", "Steamcloud Arrowhead"], category: "Arrowheads", mod: "crafters_kit" },
  { result: "Stunning Arrowhead", ingredients: ["Water Essence", "Water Arrowhead"], category: "Arrowheads" },
  { result: "Water Arrowhead", ingredients: ["Water", "Arrowhead"], category: "Arrowheads" },

  // ----------------------- ARROWS -----------------------
  { result: "Arrow", ingredients: ["Arrow Shaft", "Arrowhead"], category: "Arrows" },
  { result: "Blessed Water Arrow", ingredients: ["Arrow Shaft", "Blessed Water Arrowhead"], category: "Arrows" },
  { result: "Blessed Water Arrow", ingredients: ["Source Orb", "Water Arrow"], category: "Arrows" },
  { result: "Charming Arrow", ingredients: ["Arrow Shaft", "Charming Arrowhead"], category: "Arrows" },
  { result: "Charming Arrow", ingredients: ["Honey", "Arrow"], category: "Arrows" },
  { result: "Cursed Fire Arrow", ingredients: ["Arrow Shaft", "Cursed Fire Arrowhead"], category: "Arrows" },
  { result: "Cursed Fire Arrow", ingredients: ["Source Orb", "Fire Arrow"], category: "Arrows" },
  { result: "Explosive Arrow", ingredients: ["Arrow Shaft", "Explosive Arrowhead"], category: "Arrows" },
  { result: "Explosive Arrow", ingredients: ["any oil source", "Fire Arrow"], category: "Arrows" },
  { result: "Fire Arrow", ingredients: ["any Fire Essence", "Arrow"], category: "Arrows" },
  { result: "Fire Arrow", ingredients: ["Arrow Shaft", "Fire Arrowhead"], category: "Arrows" },
  { result: "Fire Arrow", ingredients: ["Fire Arrowhead", "Oil"], category: "Arrows", mod: "crafters_kit" },
  { result: "Freezing Arrow", ingredients: ["any Water Essence", "Arrow"], category: "Arrows" },
  { result: "Freezing Arrow", ingredients: ["Arrow Shaft", "Freezing Arrowhead"], category: "Arrows" },
  { result: "Knockdown Arrow", ingredients: ["Arrow Shaft", "Knockdown Arrowhead"], category: "Arrows" },
  { result: "Poison Arrow", ingredients: ["Arrow Shaft", "Poisoned Arrowhead"], category: "Arrows" },
  { result: "Poison Arrow", ingredients: ["Poison", "Arrow"], category: "Arrows" },
  { result: "Poisoncloud Arrow", ingredients: ["any Earth Essence", "Arrow"], category: "Arrows" },
  { result: "Poisoncloud Arrow", ingredients: ["Arrow Shaft", "Poisoncloud Arrowhead"], category: "Arrows" },
  { result: "Shocking Arrow", ingredients: ["any Air Essence", "Arrow"], category: "Arrows" },
  { result: "Shocking Arrow", ingredients: ["Arrow Shaft", "Shocking Arrowhead"], category: "Arrows" },
  { result: "Slowdown Arrow", ingredients: ["Arrow Shaft", "Slowdown Arrowhead"], category: "Arrows" },
  { result: "Slowdown Arrow", ingredients: ["Oil", "Arrow"], category: "Arrows" },
  { result: "Smokescreen Arrow", ingredients: ["Arrow Shaft", "Smokescreen Arrowhead"], category: "Arrows" },
  { result: "Static Cloud Arrow", ingredients: ["Arrow Shaft", "Static Cloud Arrowhead"], category: "Arrows" },
  { result: "Static Cloud Arrow", ingredients: ["any source of water", "Shocking Arrow"], category: "Arrows" },
  { result: "Steamcloud Arrow", ingredients: ["any air essence", "Static Cloud Arrow"], category: "Arrows", mod: "crafters_kit" },
  { result: "Stunning Arrow", ingredients: ["Water Essence", "Static Cloud Arrow"], category: "Arrows" },
  { result: "Steamcloud Arrow", ingredients: ["Arrow Shaft", "Steamcloud Arrowhead"], category: "Arrows" },
  { result: "Water Arrow", ingredients: ["Arrow Shaft", "Water Arrowhead"], category: "Arrows" },
  { result: "Water Arrow", ingredients: ["Water", "Arrow"], category: "Arrows" },

  // ----------------------- GRENADES -----------------------
  { result: "Fuse", ingredients: ["Rope", "Rope"], category: "Grenades" },
  { result: "Fuse", ingredients: ["Rope", "Cutting Tool"], category: "Grenades", mod: "crafters_kit" },
  { result: "Fuse", ingredients: ["Rat's Tail", "Oil"], category: "Grenades", mod: "crafters_kit" },
  { result: "Empty Bottle", ingredients: ["Broken Bottle", "Hammer"], category: "Grenades" },
  { result: "Empty Canister", ingredients: ["Crafter's Kit", "Metal Scraps", "Metal Scraps"], category: "Grenades", mod: "crafters_kit" },
  { result: "Blessed Ice Grenade", ingredients: ["Source Orb", "Frost Grenade"], category: "Grenades" },
  { result: "Blessed Oil Flask", ingredients: ["Source Orb", "Oil Flask"], category: "Grenades" },
  { result: "Blessed Water Balloon", ingredients: ["Source Orb", "Water Balloon"], category: "Grenades" },
  { result: "Bottle Filled With Oil", ingredients: ["Empty Bottle", "Oil"], category: "Grenades" },
  { result: "Chemical Warfare Grenade", ingredients: ["Empty Canister", "Intestines"], category: "Grenades" },
  { result: "Cluster Grenade", ingredients: ["Empty Grenade", "any Fire Essence"], category: "Grenades" },
  { result: "Cursed Cluster Grenade", ingredients: ["Source Orb", "Cluster Grenade"], category: "Grenades" },
  { result: "Cursed Firestorm Grenade", ingredients: ["Source Orb", "Firestorm Grenade"], category: "Grenades" },
  { result: "Cursed Poison Flask", ingredients: ["Source Orb", "Poison Flask"], category: "Grenades" },
  { result: "Eraser Grenade", ingredients: ["Thunderbolt Grenade", "Distinctive Puffball"], category: "Grenades", mod: "crafters_kit" },
  { result: "Firestorm Grenade", ingredients: ["Bottle Filled With Oil", "Fuse"], category: "Grenades" },
  { result: "Frost Grenade", ingredients: ["Empty Grenade", "any Water Essence"], category: "Grenades" },
  { result: "Holy Hand Grenade", ingredients: ["Sovereign's Orb", "Pixie Dust / Starfish"], category: "Grenades" },
  { result: "Love Grenade", ingredients: ["Empty Perfume Bottle", "Honey / Pixie Dust"], category: "Grenades" },
  { result: "MindMaggots Grenade", ingredients: ["Empty Grenade", "Jar of MindMaggots"], category: "Grenades" },
  { result: "Nailbomb Grenade", ingredients: ["Empty Grenade", "Broken Bottle / Nails"], category: "Grenades" },
  { result: "Nailbomb Grenade", ingredients: ["Empty Grenade", "Metal Scraps"], category: "Grenades", mod: "crafters_kit" },
  { result: "Nailbomb Grenade", ingredients: ["Empty Grenade", "Scale Scraps"], category: "Grenades", mod: "crafters_kit" },
  { result: "Oil Flask", ingredients: ["Empty Flask", "Oil"], category: "Grenades" },
  { result: "Poison Cloud Grenade", ingredients: ["Empty Canister", "Poison / Rotten Eggs"], category: "Grenades" },
  { result: "Poison Flask", ingredients: ["Empty Flask", "Poison"], category: "Grenades" },
  { result: "Razzle Dazzle Grenade", ingredients: ["Empty Canister", "Air Resistance Potion / Jellyroom"], category: "Grenades" },
  { result: "Smoke Grenade", ingredients: ["Oil", "Empty Canister", "Wood"], category: "Grenades", mod: "crafters_kit" },
  { result: "Terror Grenade", ingredients: ["Empty Canister", "Tormented Soul"], category: "Grenades" },
  { result: "Terror Grenade", ingredients: ["Empty Canister", "High Quality Tormented Soul"], category: "Grenades" },
  { result: "Thunderbolt Grenade", ingredients: ["Empty Canister", "any Air Essence"], category: "Grenades" },
  { result: "Tremor Grenade", ingredients: ["Empty Canister", "any Earth Essence"], category: "Grenades" },
  { result: "Water Balloon", ingredients: ["Intestines", "Water"], category: "Grenades" },
  { result: "Soggy Nailbomb", ingredients: ["Nailbomb Grenade", "Water Balloon", "Rope"], category: "Grenades", mod: "crafters_kit" },
  { result: "Poison Nailbomb", ingredients: ["Nailbomb Grenade", "Poison Flask", "Rope"], category: "Grenades", mod: "crafters_kit" },
  { result: "Oily Nailbomb", ingredients: ["Nailbomb Grenade", "Oil Flask", "Rope"], category: "Grenades", mod: "crafters_kit" },
  { result: "Flaming Nailbomb", ingredients: ["Nailbomb Grenade", "Firestorm Grenade", "Rope"], category: "Grenades", mod: "crafters_kit" },
  { result: "Icy Nailbomb", ingredients: ["Nailbomb Grenade", "Frost Grenade", "Rope"], category: "Grenades", mod: "crafters_kit" },
  { result: "Water Dazzler Grenade", ingredients: ["Flashbang Grenade", "Water Balloon", "Rope"], category: "Grenades", mod: "crafters_kit" },
  { result: "Poison Dazzler Grenade", ingredients: ["Flashbang Grenade", "Poison Flask", "Rope"], category: "Grenades", mod: "crafters_kit" },
  { result: "Oil Dazzler Grenade", ingredients: ["Flashbang Grenade", "Oil Flask", "Rope"], category: "Grenades", mod: "crafters_kit" },
  { result: "Flame Dazzler Grenade", ingredients: ["Flashbang Grenade", "Firestorm Grenade", "Rope"], category: "Grenades", mod: "crafters_kit" },
  { result: "Ice Dazzler Grenade", ingredients: ["Flashbang Grenade", "Frost Grenade", "Rope"], category: "Grenades", mod: "crafters_kit" },
  { result: "Stunning Water Grenade", ingredients: ["Taser Grenade", "Water Balloon", "Rope"], category: "Grenades", mod: "crafters_kit" },
  { result: "Stunning Poison Grenade", ingredients: ["Taser Grenade", "Poison Flask", "Rope"], category: "Grenades", mod: "crafters_kit" },
  { result: "Stunning Oil Grenade", ingredients: ["Taser Grenade", "Oil Flask", "Rope"], category: "Grenades", mod: "crafters_kit" },
  { result: "Stunning Flame Grenade", ingredients: ["Taser Grenade", "Firestorm Grenade", "Rope"], category: "Grenades", mod: "crafters_kit" },
  { result: "Stunning Ice Grenade", ingredients: ["Taser Grenade", "Frost Grenade", "Rope"], category: "Grenades", mod: "crafters_kit" },

  // ----------------------- POTIONS - healing -----------------------
  { result: "Giant Healing Potion", ingredients: ["Huge Healing Potion", "Huge Healing Potion"], category: "Potions (Healing)" },
  { result: "Giant Healing Potion", ingredients: ["Huge Healing Potion", "Ultimate Augmentor Herb"], category: "Potions (Healing)" },
  { result: "Healing Elixir", ingredients: ["Empty Potion Bottle", "Yarrow Flower"], category: "Potions (Healing)" },
  { result: "Healing Potion", ingredients: ["Large Poison Bottle", "Red Fabric Dye"], category: "Potions (Healing)" },
  { result: "Healing Potion", ingredients: ["Medium Healing Potion", "Augmentor"], category: "Potions (Healing)" },
  { result: "Healing Potion", ingredients: ["Medium Healing Potion", "High Quality Augmentor"], category: "Potions (Healing)" },
  { result: "Healing Potion", ingredients: ["Medium Healing Potion", "Medium Healing Potion"], category: "Potions (Healing)" },
  { result: "Healing Potion", ingredients: ["Medium Healing Potion", "Ultimate Augmentor Herb"], category: "Potions (Healing)" },
  { result: "Huge Healing Potion", ingredients: ["Healing Potion", "Healing Potion"], category: "Potions (Healing)" },
  { result: "Huge Healing Potion", ingredients: ["Healing Potion", "High Quality Augmentor"], category: "Potions (Healing)" },
  { result: "Huge Healing Potion", ingredients: ["Healing Potion", "Ultimate Augmentor Herb"], category: "Potions (Healing)" },
  { result: "Medium Healing Potion", ingredients: ["Minor Healing Potion", "Augmentor"], category: "Potions (Healing)" },
  { result: "Medium Healing Potion", ingredients: ["Minor Healing Potion", "High Quality Augmentor"], category: "Potions (Healing)" },
  { result: "Medium Healing Potion", ingredients: ["Minor Healing Potion", "Minor Healing Potion"], category: "Potions (Healing)" },
  { result: "Medium Healing Potion", ingredients: ["Minor Healing Potion", "Ultimate Augmentor Herb"], category: "Potions (Healing)" },
  { result: "Minor Healing Potion", ingredients: ["Empty Potion Bottle", "Penny Bun Mushroom"], category: "Potions (Healing)" },
  { result: "Poison Elixir", ingredients: ["Healing Elixir", "Zaikk's Talon"], category: "Potions (Healing)" },

  // ----------------------- POTIONS - poisons -----------------------
  { result: "Giant Poison Vial", ingredients: ["Giant Healing Potion", "Zaikk's Talon"], category: "Potions (Poison)" },
  { result: "Giant Poison Vial", ingredients: ["Huge Poison Vial", "Huge Poison Vial"], category: "Potions (Poison)" },
  { result: "Giant Poison Vial", ingredients: ["Huge Poison Vial", "Ultimate Augmentor Herb"], category: "Potions (Poison)" },
  { result: "Huge Poison Vial", ingredients: ["Huge Healing Potion", "Zaikk's Talon"], category: "Potions (Poison)" },
  { result: "Huge Poison Vial", ingredients: ["Large Poison Bottle", "High Quality Augmentor"], category: "Potions (Poison)" },
  { result: "Huge Poison Vial", ingredients: ["Large Poison Bottle", "Large Poison Bottle"], category: "Potions (Poison)" },
  { result: "Huge Poison Vial", ingredients: ["Large Poison Bottle", "Ultimate Augmentor Herb"], category: "Potions (Poison)" },
  { result: "Large Poison Bottle", ingredients: ["Healing Potion", "Zaikk's Talon"], category: "Potions (Poison)" },
  { result: "Large Poison Bottle", ingredients: ["Medium Poison Bottle", "Augmentor"], category: "Potions (Poison)" },
  { result: "Large Poison Bottle", ingredients: ["Medium Poison Bottle", "High Quality Augmentor"], category: "Potions (Poison)" },
  { result: "Large Poison Bottle", ingredients: ["Medium Poison Bottle", "Medium Poison Bottle"], category: "Potions (Poison)" },
  { result: "Medium Poison Bottle", ingredients: ["Medium Healing Potion", "Red Fabric Dye"], category: "Potions (Poison)" },
  { result: "Medium Poison Bottle", ingredients: ["Medium Healing Potion", "Zaikk's Talon"], category: "Potions (Poison)" },
  { result: "Medium Poison Bottle", ingredients: ["Small Poison Bottle", "Augmentor"], category: "Potions (Poison)" },
  { result: "Medium Poison Bottle", ingredients: ["Small Poison Bottle", "High Quality Augmentor"], category: "Potions (Poison)" },
  { result: "Medium Poison Bottle", ingredients: ["Small Poison Bottle", "Small Poison Bottle"], category: "Potions (Poison)" },
  { result: "Small Poison Bottle", ingredients: ["Minor Healing Potion", "Red Fabric Dye"], category: "Potions (Poison)" },
  { result: "Poison Elixir", ingredients: ["Healing Elixir", "Zaikk's Talon"], category: "Potions (Poison)" },
  { result: "Poisoned Dinner", ingredients: ["Dinner", "Zaikk's Talon"], category: "Potions (Poison)", effect: "Undead gain +2 Strength buff" },
  { result: "Small Poison Bottle", ingredients: ["Empty Potion Bottle", "Fly Agaric Mushroom"], category: "Potions (Poison)" },
  { result: "Small Poison Bottle", ingredients: ["Empty Potion Bottle", "Ooze Barrel"], category: "Potions (Poison)" },
  { result: "Small Poison Bottle", ingredients: ["Minor Healing Potion", "Zaikk's Talon"], category: "Potions (Poison)" },
  { result: "Void-Enhanced Poison", ingredients: ["Small Poison Bottle", "Void-Touched Livewood Fragments"], category: "Potions (Poison)" },

  // ----------------------- POTIONS - resists and armour -----------------------
  { result: "Huge Air Resistance Potion", ingredients: ["Large Air Resistance Potion", "Large Air Resistance Potion"], category: "Potions (Resist & Armour)" },
  { result: "Huge Air Resistance Potion", ingredients: ["Large Air Resistance Potion", "Ultimate Augmentor Herb"], category: "Potions (Resist & Armour)" },
  { result: "Huge Earth Resistance Potion", ingredients: ["Large Earth Resistance Potion", "Large Earth Resistance Potion"], category: "Potions (Resist & Armour)" },
  { result: "Huge Earth Resistance Potion", ingredients: ["Large Earth Resistance Potion", "Ultimate Augmentor Herb"], category: "Potions (Resist & Armour)" },
  { result: "Huge Fire Resistance Potion", ingredients: ["Large Fire Resistance Potion", "Large Fire Resistance Potion"], category: "Potions (Resist & Armour)" },
  { result: "Huge Fire Resistance Potion", ingredients: ["Large Fire Resistance Potion", "Ultimate Augmentor Herb"], category: "Potions (Resist & Armour)" },
  { result: "Huge Water Resistance Potion", ingredients: ["Large Water Resistance Potion", "Large Water Resistance Potion"], category: "Potions (Resist & Armour)" },
  { result: "Huge Water Resistance Potion", ingredients: ["Large Water Resistance Potion", "Ultimate Augmentor Herb"], category: "Potions (Resist & Armour)" },
  { result: "Large Air Resistance Potion", ingredients: ["Medium Air Resistance Potion", "High Quality Augmentor"], category: "Potions (Resist & Armour)" },
  { result: "Large Air Resistance Potion", ingredients: ["Medium Air Resistance Potion", "Medium Air Resistance Potion"], category: "Potions (Resist & Armour)" },
  { result: "Large Air Resistance Potion", ingredients: ["Medium Air Resistance Potion", "Ultimate Augmentor Herb"], category: "Potions (Resist & Armour)" },
  { result: "Large Earth Resistance Potion", ingredients: ["Medium Earth Resistance Potion", "High Quality Augmentor"], category: "Potions (Resist & Armour)" },
  { result: "Large Earth Resistance Potion", ingredients: ["Medium Earth Resistance Potion", "Medium Earth Resistance Potion"], category: "Potions (Resist & Armour)" },
  { result: "Large Earth Resistance Potion", ingredients: ["Medium Earth Resistance Potion", "Ultimate Augmentor Herb"], category: "Potions (Resist & Armour)" },
  { result: "Large Fire Resistance Potion", ingredients: ["Medium Fire Resistance Potion", "High Quality Augmentor"], category: "Potions (Resist & Armour)" },
  { result: "Large Fire Resistance Potion", ingredients: ["Medium Fire Resistance Potion", "Medium Fire Resistance Potion"], category: "Potions (Resist & Armour)" },
  { result: "Large Fire Resistance Potion", ingredients: ["Medium Fire Resistance Potion", "Ultimate Augmentor Herb"], category: "Potions (Resist & Armour)" },
  { result: "Large Water Resistance Potion", ingredients: ["Medium Water Resistance Potion", "High Quality Augmentor"], category: "Potions (Resist & Armour)" },
  { result: "Large Water Resistance Potion", ingredients: ["Medium Water Resistance Potion", "Medium Water Resistance Potion"], category: "Potions (Resist & Armour)" },
  { result: "Large Water Resistance Potion", ingredients: ["Medium Water Resistance Potion", "Ultimate Augmentor Herb"], category: "Potions (Resist & Armour)" },
  { result: "Medium Air Resistance Potion", ingredients: ["Small Air Resistance Potion", "High Quality Augmentor"], category: "Potions (Resist & Armour)" },
  { result: "Medium Air Resistance Potion", ingredients: ["Small Air Resistance Potion", "Small Air Resistance Potion"], category: "Potions (Resist & Armour)" },
  { result: "Medium Air Resistance Potion", ingredients: ["Small Air Resistance Potion", "Ultimate Augmentor Herb"], category: "Potions (Resist & Armour)" },
  { result: "Medium Earth Resistance Potion", ingredients: ["Earth Resistance Potion", "Earth Resistance Potion"], category: "Potions (Resist & Armour)" },
  { result: "Medium Earth Resistance Potion", ingredients: ["Earth Resistance Potion", "High Quality Augmentor"], category: "Potions (Resist & Armour)" },
  { result: "Medium Earth Resistance Potion", ingredients: ["Earth Resistance Potion", "Ultimate Augmentor Herb"], category: "Potions (Resist & Armour)" },
  { result: "Medium Fire Resistance Potion", ingredients: ["Fire Resistance Potion", "Fire Resistance Potion"], category: "Potions (Resist & Armour)" },
  { result: "Medium Fire Resistance Potion", ingredients: ["Fire Resistance Potion", "High Quality Augmentor"], category: "Potions (Resist & Armour)" },
  { result: "Medium Fire Resistance Potion", ingredients: ["Fire Resistance Potion", "Ultimate Augmentor Herb"], category: "Potions (Resist & Armour)" },
  { result: "Medium Water Resistance Potion", ingredients: ["Water Resistance Potion", "High Quality Augmentor"], category: "Potions (Resist & Armour)" },
  { result: "Medium Water Resistance Potion", ingredients: ["Water Resistance Potion", "Ultimate Augmentor Herb"], category: "Potions (Resist & Armour)" },
  { result: "Medium Water Resistance Potion", ingredients: ["Water Resistance Potion", "Water Resistance Potion"], category: "Potions (Resist & Armour)" },
  { result: "Small Air Resistance Potion", ingredients: ["Empty Potion Bottle", "Jellyroom"], category: "Potions (Resist & Armour)" },
  { result: "Water Resistance Potion", ingredients: ["Empty Potion Bottle", "Bluegill Mushroom"], category: "Potions (Resist & Armour)" },
  { result: "Earth Resistance Potion", ingredients: ["Empty Potion Bottle", "Earth Tongue Mushroom"], category: "Potions (Resist & Armour)" },
  { result: "Fire Resistance Potion", ingredients: ["Empty Potion Bottle", "Guepinia Mushroom"], category: "Potions (Resist & Armour)" },
  { result: "Giant Magic Armour Potion", ingredients: ["Large Magic Armour Potion", "Large Magic Armour Potion"], category: "Potions (Resist & Armour)", mod: "crafters_kit" },
  { result: "Large Magic Armour Potion", ingredients: ["Medium Magic Armour Potion", "High Quality Augmentor"], category: "Potions (Resist & Armour)" },
  { result: "Large Magic Armour Potion", ingredients: ["Medium Magic Armour Potion", "Medium Magic Armour Potion"], category: "Potions (Resist & Armour)" },
  { result: "Large Magic Armour Potion", ingredients: ["Medium Magic Armour Potion", "Ultimate Augmentor Herb"], category: "Potions (Resist & Armour)" },
  { result: "Medium Magic Armour Potion", ingredients: ["Small Magic Armour Potion", "Augmentor"], category: "Potions (Resist & Armour)" },
  { result: "Medium Magic Armour Potion", ingredients: ["Small Magic Armour Potion", "High Quality Augmentor"], category: "Potions (Resist & Armour)" },
  { result: "Medium Magic Armour Potion", ingredients: ["Small Magic Armour Potion", "Small Magic Armour Potion"], category: "Potions (Resist & Armour)" },
  { result: "Small Magic Armour Potion", ingredients: ["Empty Potion Bottle", "Whisperwood"], category: "Potions (Resist & Armour)" },
  { result: "Giant Physical Armour Potion", ingredients: ["Large Physical Armour Potion", "Large Physical Armour Potion"], category: "Potions (Resist & Armour)", mod: "crafters_kit" },
  { result: "Large Physical Armour Potion", ingredients: ["Medium Physical Armour Potion", "High Quality Augmentor"], category: "Potions (Resist & Armour)" },
  { result: "Large Physical Armour Potion", ingredients: ["Medium Physical Armour Potion", "Medium Physical Armour Potion"], category: "Potions (Resist & Armour)" },
  { result: "Large Physical Armour Potion", ingredients: ["Medium Physical Armour Potion", "Ultimate Augmentor Herb"], category: "Potions (Resist & Armour)" },
  { result: "Medium Physical Armour Potion", ingredients: ["Physical Armour Potion", "Augmentor"], category: "Potions (Resist & Armour)" },
  { result: "Medium Physical Armour Potion", ingredients: ["Physical Armour Potion", "High Quality Augmentor"], category: "Potions (Resist & Armour)" },
  { result: "Medium Physical Armour Potion", ingredients: ["Physical Armour Potion", "Physical Armour Potion"], category: "Potions (Resist & Armour)" },
  { result: "Physical Armour Potion", ingredients: ["Empty Potion Bottle", "Amadouvier"], category: "Potions (Resist & Armour)" },
  { result: "Large Resist All Potion", ingredients: ["Medium Resist All Potion", "Medium Resist All Potion"], category: "Potions (Resist & Armour)" },
  { result: "Large Resist All Potion", ingredients: ["Medium Resist All Potion", "Ultimate Augmentor Herb"], category: "Potions (Resist & Armour)" },
  { result: "Medium Resist All Potion", ingredients: ["Minor Resist All Potion", "High Quality Augmentor"], category: "Potions (Resist & Armour)" },
  { result: "Medium Resist All Potion", ingredients: ["Minor Resist All Potion", "Minor Resist All Potion"], category: "Potions (Resist & Armour)" },
  { result: "Medium Resist All Potion", ingredients: ["Minor Resist All Potion", "Ultimate Augmentor Herb"], category: "Potions (Resist & Armour)" },
  { result: "Minor Resist All Potion", ingredients: ["Empty Potion Bottle", "Trumpet of Death"], category: "Potions (Resist & Armour)" },

  // ----------------------- POTIONS - stats, invis, stoneskin -----------------------
  { result: "Blood Rose Elixir", ingredients: ["Empty Potion Bottle", "Blood Rose"], category: "Potions (Stats)" },
  { result: "Invisibility Potion", ingredients: ["Empty Potion Bottle", "Chanterelle"], category: "Potions (Stats)" },
  { result: "Minor Constitution Potion", ingredients: ["Empty Potion Bottle", "Farhangite"], category: "Potions (Stats)" },
  { result: "Minor Finesse Potion", ingredients: ["Empty Potion Bottle", "Boletus"], category: "Potions (Stats)" },
  { result: "Minor Intelligence Potion", ingredients: ["Empty Potion Bottle", "Calocera"], category: "Potions (Stats)" },
  { result: "Minor Strength Potion", ingredients: ["Empty Potion Bottle", "Amethyst Deceiver"], category: "Potions (Stats)" },
  { result: "Minor Wits Potion", ingredients: ["Empty Potion Bottle", "Puffball"], category: "Potions (Stats)" },
  { result: "Potion of Jellyfish Skin", ingredients: ["Empty Potion Bottle", "any Air Essence"], category: "Potions (Stats)" },
  { result: "Potion of Nimble Tumble", ingredients: ["Empty Potion Bottle", "any Water Essence"], category: "Potions (Stats)" },
  { result: "Potion of Strong Will", ingredients: ["Empty Potion Bottle", "any Fire Essence"], category: "Potions (Stats)" },
  { result: "Stoneskin Potion", ingredients: ["Empty Potion Bottle", "any Earth Essence"], category: "Potions (Stats)" },

  // ----------------------- POTIONS - Herb Garden mod -----------------------
  { result: "Potion of Vitality", ingredients: ["Source Orb", "Distinctive Wizard's Hat Agaric", "Minor Constitution Potion"], category: "Potions (Herb Garden)", mod: "herb_garden", effect: "+10% Maximum Vitality for 3 turns" },
  { result: "Potion of Focus", ingredients: ["Source Orb", "Distinctive Farhangite", "Large Strength Potion"], category: "Potions (Herb Garden)", mod: "herb_garden", effect: "+10% Critical Chance for 3 turns" },
  { result: "Potion of Authority", ingredients: ["Source Orb", "Distinctive Farhangite", "Large Intelligence Potion"], category: "Potions (Herb Garden)", mod: "herb_garden", effect: "2 Persuasion for 3 turns" },
  { result: "Potion of Nimble Fingers", ingredients: ["Source Orb", "Distinctive Puffball", "Large Wits Potion"], category: "Potions (Herb Garden)", mod: "herb_garden", effect: "2 Thievery for 3 turns" },
  { result: "Potion of Allure", ingredients: ["Source Orb", "Distinctive Drudanae", "Large Finesse Potion"], category: "Potions (Herb Garden)", mod: "herb_garden", effect: "2 Bartering for 3 turns" },
  { result: "Potion of Power", ingredients: ["Source Orb", "Distinctive Wizard's Hat Agaric", "Large Strength Potion"], category: "Potions (Herb Garden)", mod: "herb_garden", effect: "+10% Damage Increase for 3 turns" },
  { result: "Small Potion of Shadow", ingredients: ["Source Orb", "Distinctive Trumpet of Death", "Medium Invisibility Potion"], category: "Potions (Herb Garden)", mod: "herb_garden", effect: "1 Sneaking for 3 turns" },
  { result: "Medium Potion of Shadow", ingredients: ["Source Orb", "Distinctive Trumpet of Death", "Medium Finesse Potion"], category: "Potions (Herb Garden)", mod: "herb_garden", effect: "2 Sneaking for 3 turns" },
  { result: "Large Potion of Shadow", ingredients: ["Source Orb", "Distinctive Trumpet of Death", "Large Finesse Potion"], category: "Potions (Herb Garden)", mod: "herb_garden", effect: "3 Sneaking for 3 turns" },
  { result: "Draught of Strength", ingredients: ["Empty Potion Bottle", "Distinctive Wizard's Hat Agaric", "Distinctive Farhangite"], category: "Potions (Herb Garden)", mod: "herb_garden", effect: "7 Strength for 3 turns" },
  { result: "Draught of Finesse", ingredients: ["Empty Potion Bottle", "Distinctive Trumpet of Death", "Distinctive Boletus"], category: "Potions (Herb Garden)", mod: "herb_garden", effect: "7 Finesse for 3 turns" },
  { result: "Draught of Constitution", ingredients: ["Empty Potion Bottle", "Distinctive Puffball", "Distinctive Drudanae"], category: "Potions (Herb Garden)", mod: "herb_garden", effect: "7 Constitution for 3 turns" },
  { result: "Draught of Wits", ingredients: ["Empty Potion Bottle", "Distinctive Trumpet of Death", "Distinctive Amadouvier"], category: "Potions (Herb Garden)", mod: "herb_garden", effect: "7 Wits for 3 turns" },
  { result: "Draught of Intelligence", ingredients: ["Empty Potion Bottle", "Distinctive Wizard's Hat Agaric", "Distinctive Whisperwood"], category: "Potions (Herb Garden)", mod: "herb_garden", effect: "7 Intelligence for 3 turns" },
  { result: "Draught of Speed", ingredients: ["Empty Potion Bottle", "Distinctive Drudanae", "Air Essence"], category: "Potions (Herb Garden)", mod: "herb_garden", effect: "50% Movement Speed for 3 turns" },

  // ----------------------- CONSUMABLE -----------------------
  { result: "Apple Juice", ingredients: ["Empty Cup", "Apple"], category: "Consumable" },
  { result: "Apple Pie Dough", ingredients: ["Apple", "Dough"], category: "Consumable" },
  { result: "Apple Pie", ingredients: ["Apple Pie Dough", "Oven"], category: "Consumable" },
  { result: "Boiled Potato", ingredients: ["Potato", "Boiling Pot"], category: "Consumable" },
  { result: "Bottle of Beer", ingredients: ["Beer Barrel", "Empty Bottle"], category: "Consumable" },
  { result: "Bottle of Water", ingredients: ["Water Barrel", "Empty Bottle"], category: "Consumable" },
  { result: "Bottle of Wine", ingredients: ["Wine Barrel", "Empty Bottle"], category: "Consumable" },
  { result: "Bread", ingredients: ["Dough", "Oven"], category: "Consumable" },
  { result: "Bucket and Cup of Milk", ingredients: ["Bucket with Milk", "Empty Cup"], category: "Consumable" },
  { result: "Cheese Bread Dough", ingredients: ["Cheese", "Dough"], category: "Consumable" },
  { result: "Cheese Bread", ingredients: ["Cheese Bread Dough", "Oven"], category: "Consumable" },
  { result: "Cold Fries", ingredients: ["Dagger", "Potato"], category: "Consumable" },
  { result: "Cold Fries", ingredients: ["Knife", "Potato"], category: "Consumable" },
  { result: "Cold Mashed Potatoes", ingredients: ["Potato", "Hammer"], category: "Consumable" },
  { result: "Cup of Lemonade", ingredients: ["Empty Cup", "Lemon"], category: "Consumable" },
  { result: "Cup of Lemonade", ingredients: ["Empty Mug", "Lemon"], category: "Consumable" },
  { result: "Cooking Station", ingredients: ["Cooking Pot", "Campfire"], category: "Consumable" },
  { result: "Cup of Tea", ingredients: ["Tea Herbs", "Cup of Water"], category: "Consumable" },
  { result: "Cup of Water", ingredients: ["Empty Cup", "Water"], category: "Consumable" },
  { result: "Dinner", ingredients: ["Eggs", "Oven / Boiling Pot / Cooking Station"], category: "Consumable" },
  { result: "Dinner", ingredients: ["FoodFish", "Oven / Boiling Pot / Cooking Station"], category: "Consumable" },
  { result: "Dinner", ingredients: ["Meat", "Oven / Boiling Pot / Cooking Station"], category: "Consumable" },
  { result: "Dinner", ingredients: ["Raw Bird Leg", "Oven / Boiling Pot / Cooking Station"], category: "Consumable" },
  { result: "Dinner", ingredients: ["Raw Mutton", "Oven / Boiling Pot / Cooking Station"], category: "Consumable" },
  { result: "Dinner", ingredients: ["Raw Red Meat", "Oven / Boiling Pot / Cooking Station"], category: "Consumable" },
  { result: "Dough", ingredients: ["Flour", "Milk"], category: "Consumable" },
  { result: "Dough", ingredients: ["Flour", "Milk", "Eggs"], category: "Consumable" },
  { result: "Dough", ingredients: ["Flour", "Water"], category: "Consumable" },
  { result: "Dwarven Stew", ingredients: ["Dinner", "Beer"], category: "Consumable" },
  { result: "Elven Stew", ingredients: ["Dinner", "Tomato Sauce"], category: "Consumable" },
  { result: "Fish Pie Dough", ingredients: ["FoodFish", "Dough"], category: "Consumable" },
  { result: "Fish Pie", ingredients: ["Fish Pie Dough", "Oven"], category: "Consumable" },
  { result: "Flour", ingredients: ["Wheat", "Mortar and Pestle"], category: "Consumable" },
  { result: "Glass of Wine", ingredients: ["Empty Cup", "Grapes"], category: "Consumable" },
  { result: "Glass of Wine", ingredients: ["Empty Cup", "Wine"], category: "Consumable" },
  { result: "Jar of Honey", ingredients: ["Empty Honey Jar", "Beehive"], category: "Consumable" },
  { result: "Mashed Potatoes", ingredients: ["Boiled Potato", "Milk"], category: "Consumable" },
  { result: "Mashed Potatoes", ingredients: ["Cold Mashed Potatoes", "Oven / Boiling Pot / Cooking Station"], category: "Consumable" },
  { result: "Milk and Honey", ingredients: ["Jar of Honey", "Milk"], category: "Consumable", effect: "Jar is consumed (not returned)" },
  { result: "Milk", ingredients: ["Milk Jug", "Empty Cup"], category: "Consumable" },
  { result: "Mug of Beer", ingredients: ["Empty Mug", "Beer"], category: "Consumable" },
  { result: "Mug of Tea", ingredients: ["Tea Herbs", "Mug of Water"], category: "Consumable" },
  { result: "Mug of Water", ingredients: ["Empty Mug", "Water"], category: "Consumable" },
  { result: "Mug of Wine", ingredients: ["Empty Mug", "Grapes"], category: "Consumable" },
  { result: "Mug of Wine", ingredients: ["Empty Mug", "Wine"], category: "Consumable" },
  { result: "Orange Juice", ingredients: ["Empty Cup", "Orange"], category: "Consumable" },
  { result: "Pizza Dough", ingredients: ["Tomato Sauce", "Dough"], category: "Consumable" },
  { result: "Pizza", ingredients: ["Pizza Dough", "Oven"], category: "Consumable" },
  { result: "Porridge", ingredients: ["Wheat", "Milk"], category: "Consumable" },
  { result: "Potato Porridge", ingredients: ["Potato", "Milk"], category: "Consumable" },
  { result: "Pumpkin Soup", ingredients: ["Pumpkin Part", "Oven / Boiling Pot / Cooking Station"], category: "Consumable" },
  { result: "Pumpkin Soup", ingredients: ["Pumpkin Peel", "Oven / Boiling Pot / Cooking Station"], category: "Consumable" },
  { result: "Pumpkin Soup", ingredients: ["Pumpkin", "Oven / Boiling Pot / Cooking Station"], category: "Consumable" },
  { result: "Rivellon Fries", ingredients: ["Cold Fries", "Boiling Pot"], category: "Consumable" },
  { result: "Tainted Stew", ingredients: ["Meaty Stew", "Any void-tainted fish", "Boiling Pot"], category: "Consumable" },
  { result: "Tomato Sauce", ingredients: ["Tomato", "Hammer"], category: "Consumable" }
];

/* --------- SKILLBOOKS & SCROLLS (generated programmatically below to keep file lean) --------- */
(function () {
  var SB = window.RECIPES;

  // Common skillbook blanks per element (Herb Garden / Crafter's Kit prerequisites)
  var blanks = {
    Air: "distinctive tea", Earth: "distinctive Amadouvier", Fire: "Distinctive Boletus",
    Water: "distinctive Farhangite", Necromancy: "Distinctive Trumpet of Death",
    Summoning: "distinctive Drudenae", Polymorph: "distinctive Whisperwood"
  };
  Object.keys(blanks).forEach(function (el) {
    var cat = "Skillbooks (" + el + ")";
    SB.push({ result: "Leather Cover", ingredients: ["Knife", "Leather Scraps", "Leather Scraps"], category: cat, mod: "herb_garden" });
    SB.push({ result: "Quill", ingredients: ["Feather", "Cutting Tool"], category: cat, mod: "crafters_kit" });
    SB.push({ result: "Blank " + el + " Skillbook", ingredients: ["Leather Cover", "Quill", blanks[el]], category: cat, mod: "herb_garden" });
    SB.push({ result: "High Tier Blank " + el + " Skillbook", ingredients: ["Blank " + el + " Skillbook", "Quill", blanks[el]], category: cat, mod: "herb_garden" });
  });

  // Scroll-into-skillbook recipes: [resultSkill, blankType, scroll, element]
  var scrollBooks = [
    // AIR
    ["Apportation", "Blank", "Apportation Scroll", "Air"],
    ["Blinding Radiance", "High", "Blinding Radiance Scroll", "Air"],
    ["Chain Lightning", "High", "Chain Lightning Scroll", "Air"],
    ["Closed Circuit", "High", "Closed Circuit Scroll", "Air"],
    ["Dazing Bolt", "Blank", "Dazing Bolt Scroll", "Air"],
    ["Electric Discharge", "Blank", "Electric Discharge Scroll", "Air"],
    ["Favourable Wind", "Blank", "Favourable Wind Scroll", "Air"],
    ["Nether Swap", "High", "Nether Swap Scroll", "Air"],
    ["Pressure Spike", "Blank", "Pressure Spike Scroll", "Air"],
    ["Shocking Touch", "Blank", "Shocking Touch Scroll", "Air"],
    ["Superconductor", "High", "Superconductor Scroll", "Air"],
    ["Teleportation", "Blank", "Teleportation Scroll", "Air"],
    ["Thunderstorm", "High", "Thunderstorm Scroll", "Air"],
    ["Tornado", "High", "Tornado Scroll", "Air"],
    // EARTH
    ["Acid Spores", "High", "Acid Spores Scroll", "Earth"],
    ["Artillery Plant", "Blank", "Artillery Plant Scroll", "Earth"],
    ["Contamination", "Blank", "Contamination Scroll", "Earth"],
    ["Earthquake", "Blank", "Earthquake Scroll", "Earth"],
    ["Fortify", "Blank", "Fortify Scroll", "Earth"],
    ["Fossil Strike", "Blank", "Fossil Strike Scroll", "Earth"],
    ["Impalement", "Blank", "Impalement Scroll", "Earth"],
    ["Living Wall", "High", "Living Wall Scroll", "Earth"],
    ["Mend Metal", "Blank", "Mend Metal Scroll", "Earth"],
    ["Poison Dart", "Blank", "Poison Dart Scroll", "Earth"],
    ["Poison Wave", "Blank", "Poison Wave Scroll", "Earth"],
    ["Pyroclastic Eruption", "High", "Pyroclastic Eruption Scroll", "Earth"],
    ["Reactive Armour", "Blank", "Reactive Armour Scroll", "Earth"],
    ["Siphon Poison", "High", "Siphon Poison Scroll", "Earth"],
    ["Worm Tremor", "Blank", "Worm Tremor Scroll", "Earth"],
    // FIRE
    ["Bleed Fire", "Blank", "Bleed Fire Scroll", "Fire"],
    ["Epidemic Of Fire", "High", "Epidemic Of Fire Scroll", "Fire"],
    ["Fire Whip", "Blank", "Fire Whip Scroll", "Fire"],
    ["Fireball", "Blank", "Fireball Scroll", "Fire"],
    ["Firebrand", "High", "Firebrand Scroll", "Fire"],
    ["Flaming Crescendo", "High", "Flaming Crescendo Scroll", "Fire"],
    ["Flaming Tongues", "Blank", "Flaming Tongues Scroll", "Fire"],
    ["Haste", "Blank", "Haste Scroll", "Fire"],
    ["Ignition", "Blank", "Ignition Scroll", "Fire"],
    ["Laser Ray", "Blank", "Laser Ray Scroll", "Fire"],
    ["Meteor Shower", "High", "Meteor Shower Scroll", "Fire"],
    ["Peace of Mind", "Blank", "Peace of Mind Scroll", "Fire"],
    ["Searing Daggers", "Blank", "Searing Daggers Scroll", "Fire"],
    ["Spontaneous Combustion", "Blank", "Spontaneous Combustion Scroll", "Fire"],
    ["Summon Fire Slug", "Blank", "Summon Fire Slug Scroll", "Fire"],
    ["Supernova", "Blank", "Supernova Scroll", "Fire"],
    // WATER
    ["Arcane Stitch", "Blank", "Arcane Stitch Scroll", "Water"],
    ["Armour of Frost", "Blank", "Armour of Frost Scroll", "Water"],
    ["Cryogenic Stasis", "Blank", "Cryogenic Stasis Scroll", "Water"],
    ["Deep Freeze", "High", "Deep Freeze Scroll", "Water"],
    ["Global Cooling", "High", "Global Cooling Scroll", "Water"],
    ["Hail Strike", "Blank", "Hail Strike Scroll", "Water"],
    ["Healing Ritual", "High", "Healing Ritual Scroll", "Water"],
    ["Ice Breaker", "High", "Ice Breaker Scroll", "Water"],
    ["Ice Fan", "Blank", "Ice Fan Scroll", "Water"],
    ["Rain", "Blank", "Rain Scroll", "Water"],
    ["Restoration", "Blank", "Restoration Scroll", "Water"],
    ["Soothing Cold", "Blank", "Soothing Cold Scroll", "Water"],
    ["Steam Lance", "High", "Steam Lance Scroll", "Water"],
    ["Winter Blast", "Blank", "Winter Blast Scroll", "Water"],
    // NECROMANCY
    ["Black Shroud", "Blank", "Black Shroud Scroll", "Necromancy"],
    ["Blood Rain", "Blank", "Raining Blood Scroll", "Necromancy"],
    ["Blood Sucker", "Blank", "Blood Sucker Scroll", "Necromancy"],
    ["Bone Cage", "Blank", "Bone Cage Scroll", "Necromancy"],
    ["Death Wish", "Blank", "Death Wish Scroll", "Necromancy"],
    ["Decaying Touch", "Blank", "Decaying Touch Scroll", "Necromancy"],
    ["Grasp of the Starved", "High", "Grasp of the Starved Scroll", "Necromancy"],
    ["Infect", "Blank", "Infect Scroll", "Necromancy"],
    ["Living on the Edge", "Blank", "Living on the Edge Scroll", "Necromancy"],
    ["Mosquito Swarm", "Blank", "Mosquito Swarm Scroll", "Necromancy"],
    ["Raise Bloated Corpse", "Blank", "Raise Bloated Corpse Scroll", "Necromancy"],
    ["Raise Bone Widow", "Blank", "Raise Bone Widow Scroll", "Necromancy"],
    ["Shackles of Pain", "Blank", "Shackles of Pain Scroll", "Necromancy"],
    ["Silencing Stare", "High", "Silencing Stare Scroll", "Necromancy"],
    ["Totems of the Necromancer", "High", "Totems of the Necromancer Scroll", "Necromancy"],
    // SUMMONING
    ["Cannibalise", "High", "Cannibalise Scroll", "Summoning"],
    ["Conjure Incarnate", "Blank", "Conjure Incarnate Scroll", "Summoning"],
    ["Dimensional Bolt", "Blank", "Dimensional Bolt Scroll", "Summoning"],
    ["Dominate Mind", "Blank", "Charm Scroll", "Summoning"],
    ["Door to Eternity", "High", "Door to Eternity Scroll", "Summoning"],
    ["Elemental Totem", "Blank", "Elemental Totem Scroll", "Summoning"],
    ["Ethereal Storm", "High", "Ethereal Storm Scroll", "Summoning"],
    ["Farsight Infusion", "Blank", "Farsight Infusion Scroll", "Summoning"],
    ["Planar Gateway", "Blank", "Planar Gateway Scroll", "Summoning"],
    ["Power Infusion", "Blank", "Power Infusion Scroll", "Summoning"],
    ["Rallying Cry", "Blank", "Rallying Cry Scroll", "Summoning"],
    ["Shadow Infusion", "Blank", "Shadow Infusion Scroll", "Summoning"],
    ["Soul Mate", "Blank", "Soul Mate Scroll", "Summoning"],
    ["Supercharger", "Blank", "Supercharger Scroll", "Summoning"],
    ["Warp Infusion", "High", "Warp Infusion Scroll", "Summoning"],
    // POLYMORPH
    ["Apotheosis", "High", "Apotheosis Scroll", "Polymorph"],
    ["Bull Horns", "Blank", "Bull Horns Scroll", "Polymorph"],
    ["Chameleon Cloak", "Blank", "Chameleon Cloak Scroll", "Polymorph"],
    ["Chicken Claw", "Blank", "Chicken Claw Scroll", "Polymorph"],
    ["Equalise", "High", "Equalise Scroll", "Polymorph"],
    ["Flay Skin", "High", "Flay Skin Scroll", "Polymorph"],
    ["Forced Exchange", "High", "Forced Exchange Scroll", "Polymorph"],
    ["Heart of Steel", "Blank", "Heart of Steel Scroll", "Polymorph"],
    ["Medusa Head", "Blank", "Medusa Head Scroll", "Polymorph"],
    ["Skin Graft", "Blank", "Skin Graft Scroll", "Polymorph"],
    ["Spider Legs", "Blank", "Spider Legs Scroll", "Polymorph"],
    ["Spread Your Wings", "Blank", "Spread Your Wings Scroll", "Polymorph"],
    ["Summon Oily Blob", "Blank", "Summon Oily Blob Scroll", "Polymorph"],
    ["Tentacle Lash", "Blank", "Tentacle Lash Scroll", "Polymorph"],
    ["Terrain Transmutation", "Blank", "Terrain Transmutation Scroll", "Polymorph"]
  ];
  scrollBooks.forEach(function (r) {
    var book = r[1] === "High" ? "High Tier Blank " + r[3] + " Skillbook" : "Blank Skillbook " + r[3];
    SB.push({ result: r[0] + " Skillbook", ingredients: [book, r[2]], category: "Skillbooks (" + r[3] + ")" });
  });

  // Combination skillbooks (element + class), with Source variants collapsed into representative entries
  var combo = [
    // Air
    ["Air", "Blessed Smoke Cloud", "any Air Skillbook", "any Rogue Skillbook with Source"],
    ["Air", "Breathing Bubble", "any Air Skillbook", "any Warrior Skillbook"],
    ["Air", "Cursed Electric Infusion", "any Air Skillbook", "any Summoning Skillbook with Source"],
    ["Air", "Electric Infusion", "any Air Skillbook", "any Summoning Skillbook"],
    ["Air", "Erratic Wisp", "any Air Skillbook", "any Ranger Skillbook"],
    ["Air", "Evasive Aura", "any Air Skillbook", "any Ranger Skillbook with Source"],
    ["Air", "Jellyfish Skin", "any Air Skillbook", "any Polymorph Skillbook with Source"],
    ["Air", "Mass Breathing Bubbles", "any Air Skillbook", "any Warrior Skillbook with Source"],
    ["Air", "Smoke Cover", "any Air Skillbook", "any Rogue Skillbook"],
    ["Air", "Vacuum Aura", "any Air Skillbook", "any Necromancy Skillbook with Source"],
    ["Air", "Vacuum Touch", "any Air Skillbook", "any Necromancy Skillbook"],
    ["Air", "Vaporise", "any Air Skillbook", "any Polymorph Skillbook"],
    // Earth
    ["Earth", "Acid Infusion", "any Earth Skillbook", "any Summoning Skillbook with Source"],
    ["Earth", "Corrosive Spray", "any Earth Skillbook", "any Necromancy Skillbook with Source"],
    ["Earth", "Corrosive Touch", "any Earth Skillbook", "any Necromancy Skillbook"],
    ["Earth", "Dust Blast", "any Earth Skillbook", "any Ranger Skillbook with Source"],
    ["Earth", "Mass Oily Carapace", "any Earth Skillbook", "any Warrior Skillbook with Source"],
    ["Earth", "Oily Carapace", "any Earth Skillbook", "any Warrior Skillbook"],
    ["Earth", "Poison Infusion", "any Earth Skillbook", "any Summoning Skillbook"],
    ["Earth", "Poisonous Skin", "any Earth Skillbook", "any Polymorph Skillbook with Source"],
    ["Earth", "Throw Dust", "any Earth Skillbook", "any Ranger Skillbook"],
    ["Earth", "Turn To Oil", "any Earth Skillbook", "any Polymorph Skillbook"],
    ["Earth", "Venom Coating", "any Earth Skillbook", "any Rogue Skillbook"],
    ["Earth", "Venomous Aura", "any Earth Skillbook", "any Rogue Skillbook with Source"],
    // Fire
    ["Fire", "Fire Infusion", "any Fire Skillbook", "any Summoning Skillbook"],
    ["Fire", "Necrofire Infusion", "any Fire Skillbook with Source", "any Summoning Skillbook"],
    ["Fire", "Corpse Explosion", "any Fire Skillbook", "any Necromancy Skillbook"],
    ["Fire", "Mass Corpse Explosion", "any Fire Skillbook with Source", "any Necromancy Skillbook"],
    ["Fire", "Sparking Swings", "any Fire Skillbook", "any Warrior Skillbook"],
    ["Fire", "Master of Sparks", "any Fire Skillbook with Source", "any Warrior Skillbook"],
    ["Fire", "Bleed Fire", "any Fire Skillbook", "any Polymorph Skillbook"],
    ["Fire", "Flaming Skin", "any Fire Skillbook with Source", "any Polymorph Skillbook"],
    ["Fire", "Sabotage", "any Fire Skillbook", "any Rogue Skillbook"],
    ["Fire", "Mass Sabotage", "any Fire Skillbook with Source", "any Rogue Skillbook"],
    ["Fire", "Explosive Trap", "any Fire Skillbook", "any Ranger Skillbook"],
    ["Fire", "Deploy Mass Traps", "any Fire Skillbook with Source", "any Ranger Skillbook"],
    // Water
    ["Water", "Cleanse Wounds", "any Water Skillbook", "any Warrior Skillbook"],
    ["Water", "Cryotherapy", "any Water Skillbook", "any Ranger Skillbook"],
    ["Water", "Mass Cleanse Wounds", "any Water Skillbook", "any Warrior Skillbook with Source"],
    ["Water", "Mass Cryotherapy", "any Water Skillbook", "any Ranger Skillbook with Source"],
    ["Water", "Vampiric Hunger Aura", "any Water Skillbook", "any Rogue Skillbook with Source"],
    ["Water", "Vampiric Hunger", "any Water Skillbook", "any Rogue Skillbook"],
    // Necromancy
    ["Necromancy", "Blood Rain", "any Water Skillbook", "any Necromancy Skillbook"],
    ["Necromancy", "Blood Storm", "any Water Skillbook with Source", "any Necromancy Skillbook"],
    // Summoning
    ["Summoning", "Water Infusion", "any Water Skillbook", "any Summoning Skillbook"],
    ["Summoning", "Blessed Ice Infusion", "any Water Skillbook with Source", "any Summoning Skillbook"],
    // Polymorph
    ["Polymorph", "Healing Tears", "any Water Skillbook", "any Polymorph Skillbook"],
    ["Polymorph", "Icy Skin", "any Water Skillbook", "any Polymorph Skillbook with Source"]
  ];
  combo.forEach(function (r) {
    SB.push({ result: r[1] + " Skillbook", ingredients: [r[2], r[3]], category: "Skillbooks (" + r[0] + ")" });
  });

  // SCROLLS: paper base
  ["Fire", "Water", "Earth", "Air", "Necromancy", "Summoning", "Polymorph"].forEach(function (el) {
    SB.push({ result: "Wood Pulp", ingredients: ["Wood Chips", "any water source"], category: "Scrolls (" + el + ")" });
    SB.push({ result: "Sheet of Paper", ingredients: ["Wood Pulp", "Oven"], category: "Scrolls (" + el + ")" });
    SB.push({ result: "Sheet of Paper", ingredients: ["Water", "Leather Scraps"], category: "Scrolls (" + el + ")", mod: "crafters_kit" });
  });

  // SCROLL crafting recipes: [scrollName, essence, reagent, element]
  var scrolls = [
    // FIRE
    ["Fire Whip Scroll", "Alien Fire Essence / High Quality Fire Essence", "Voidwoken Spike", "Fire"],
    ["Fireball Scroll", "any Fire Essence", "Sharp Claw", "Fire"],
    ["Firebrand Scroll", "Alien Fire Essence", "Fang", "Fire"],
    ["Flaming Crescendo Scroll", "Alien Fire Essence", "Needle", "Fire"],
    ["Flaming Tongues Scroll", "Alien Fire Essence / High Quality Fire Essence", "Adult Antler", "Fire"],
    ["Haste Scroll", "any Fire Essence", "Antler / Claw", "Fire"],
    ["Ignition Scroll", "any Fire Essence", "Tusk", "Fire"],
    ["Laser Ray Scroll", "Alien Fire Essence / High Quality Fire Essence", "Nails", "Fire"],
    ["Peace of Mind Scroll", "any Fire Essence", "Crab's Claw", "Fire"],
    ["Searing Daggers Scroll", "any Fire Essence", "Tooth", "Fire"],
    ["Supernova Scroll", "Alien Fire Essence / High Quality Fire Essence", "Sharp Tooth", "Fire"],
    // WATER
    ["Armour of Frost Scroll", "any Water Essence", "Bluegill Mushroom", "Water"],
    ["Deep Freeze Scroll", "Alien Water Essence", "Mackerel", "Water"],
    ["Hail Strike Scroll", "Alien Water Essence / High Quality Water Essence", "Chub Fish", "Water"],
    ["Healing Ritual Scroll", "Alien Water Essence / High Quality Water Essence", "Starfish", "Water"],
    ["Rain Scroll", "any Water Essence", "Herring", "Water"],
    ["Restoration Scroll", "any Water Essence", "Penny Bun Mushroom", "Water"],
    ["Resurrection Scroll", "any Water Essence", "any Life Essence", "Water"],
    ["Soothing Cold Scroll", "any Water Essence", "Red Snapper", "Water"],
    ["Winter Blast Scroll", "any Water Essence", "Plaice", "Water"],
    // EARTH
    ["Artillery Plant Scroll", "Source Orb", "Earth Tongue Mushroom", "Earth"],
    ["Contamination Scroll", "any Earth Essence", "Intestines", "Earth"],
    ["Earthquake Scroll", "Alien Earth Essence / High Quality Earth Essence", "Clay", "Earth"],
    ["Fortify Scroll", "any Earth Essence", "Whisperwood", "Earth"],
    ["Fossil Strike Scroll", "any Earth Essence", "Sharp Rock", "Earth"],
    ["Hungry Flower Scroll", "Source Orb", "Earth Tongue Mushroom", "Earth"],
    ["Impalement Scroll", "any Earth Essence", "Sharp Piece of Metal", "Earth"],
    ["Living Wall Scroll", "Alien Earth Essence", "Augmentor", "Earth"],
    ["Mend Metal Scroll", "any Earth Essence", "Stardust Herb", "Earth"],
    ["Mend Metal Scroll", "any Earth Essence", "Superior Stardust Herb", "Earth"],
    ["Poison Dart Scroll", "any Earth Essence", "Fly Agaric Mushroom", "Earth"],
    ["Poison Wave Scroll", "Alien Earth Essence / High Quality Earth Essence", "Slime", "Earth"],
    ["Reactive Armour Scroll", "High Quality Earth Essence / Alien Earth Essence", "Trumpet of Death", "Earth"],
    // AIR
    ["Apportation Scroll", "Alien Air Essence / High Quality Air Essence", "Rope", "Air"],
    ["Blinding Radiance Scroll", "any Air Essence", "Gold", "Air"],
    ["Electric Discharge Scroll", "any Air Essence", "Rabbit's Paw", "Air"],
    ["Favourable Wind Scroll", "any Air Essence", "Panties", "Air"],
    ["Nether Swap Scroll", "Alien Air Essence / High Quality Air Essence", "Chanterelle", "Air"],
    ["Pressure Spike Scroll", "Alien Air Essence / High Quality Air Essence", "Handkerchief", "Air"],
    ["Shocking Touch Scroll", "any Essence", "Flour", "Air"],
    ["Superconductor Scroll", "Alien Air Essence", "Jellyroom", "Air"],
    ["Teleportation Scroll", "any Air Essence", "Feather", "Air"],
    ["Tornado Scroll", "Alien Air Essence", "Fancy Feather", "Air"],
    ["Tornado Scroll", "Alien Air Essence / High Quality Air Essence", "Hair", "Air"],
    // NECROMANCY
    ["Blood Sucker Scroll", "any Shadow Essence", "Penny Bun Mushroom", "Necromancy"],
    ["Bone Cage Scroll", "Alien Shadow Essence / High Quality Shadow Essence", "Fishbone", "Necromancy"],
    ["Decaying Touch Scroll", "any Shadow Essence", "Eye", "Necromancy"],
    ["Grasp of the Starved Scroll", "High Quality Shadow Essence", "Disembodied Hand", "Necromancy"],
    ["Infect Scroll", "any Shadow Essence", "Intestines", "Necromancy"],
    ["Living on the Edge Scroll", "Alien Shadow Essence / High Quality Shadow Essence", "Giblets", "Necromancy"],
    ["Living on the Edge Scroll", "High Quality Shadow Essence", "Dirty Socks", "Necromancy"],
    ["Raise Bloated Corpse Scroll", "any Shadow Essence", "Raw Red Meat", "Necromancy"],
    ["Raise Bone Widow Scroll", "Alien Shadow Essence / High Quality Shadow Essence", "Ancient Human Skull", "Necromancy"],
    ["Shackles of Pain Scroll", "any Shadow Essence", "Skull", "Necromancy"],
    ["Silencing Stare Scroll", "Alien Shadow Essence", "Goo", "Necromancy"],
    // SUMMONING
    ["Charm Scroll", "Alien Tormented Soul", "Honey", "Summoning"],
    ["Curse Scroll", "Alien Tormented Soul / High Quality Tormented Soul", "Voidwoken Fish", "Summoning"],
    ["Dimensional Bolt Scroll", "any Tormented Soul", "Pepper", "Summoning"],
    ["Elemental Totem Scroll", "any Tormented Soul", "Doll / Wooden Figurine", "Summoning"],
    ["Rallying Cry Scroll", "any Tormented Soul", "Garlic", "Summoning"],
    ["Soul Mate Scroll", "Alien Tormented Soul / High Quality Tormented Soul", "Wheat", "Summoning"],
    // POLYMORPH
    ["Bull Horns Scroll", "any Life Essence", "Antler / Adult Antler", "Polymorph"],
    ["Chameleon Cloak Scroll", "any Life Essence", "Long Rat Tail", "Polymorph"],
    ["Chicken Claw Scroll", "any Life Essence", "Chicken Foot / Big Chicken Foot", "Polymorph"],
    ["Equalise Scroll", "Alien Life Essence", "Pilgrim's Shell", "Polymorph"],
    ["Heart of Steel Scroll", "any Life Essence", "Metal", "Polymorph"],
    ["Spider Legs Scroll", "Alien Life Essence / High Quality Life Essence", "Arthropod Leg", "Polymorph"],
    ["Spread Your Wings Scroll", "any Life Essence", "Sinew", "Polymorph"],
    ["Summon Oily Blob Scroll", "Alien Life Essence / High Quality Life Essence", "Oil", "Polymorph"],
    ["Tentacle Lash Scroll", "any Life Essence", "Rat's Tail", "Polymorph"]
  ];
  scrolls.forEach(function (r) {
    SB.push({ result: r[0], ingredients: ["Sheet of Paper / Parchment", r[1], r[2]], category: "Scrolls (" + r[3] + ")" });
  });

  // SCROLLS with Source Orb
  var srcScrolls = [
    ["Acid Spores Scroll", "Livewood"], ["Apotheosis Scroll", "Bead"], ["Black Shroud Scroll", "Creepy Eye"],
    ["Chain Lightning Scroll", "Wool / Yarn"], ["Closed Circuit Scroll", "Lucky Rabbit Paw"],
    ["Epidemic Of Fire Scroll", "Large Tusk"], ["Ethereal Storm Scroll", "Carrot"],
    ["Grasp of the Starved Scroll", "Disembodied Hand"], ["Planar Gateway Scroll", "Grapes"],
    ["Pyroclastic Eruption Scroll", "Eternal Tablet"], ["Skin Graft Scroll", "Animal Scales"],
    ["Steam Lance Scroll", "Chub Fish"]
  ];
  srcScrolls.forEach(function (r) {
    SB.push({ result: r[0], ingredients: ["Sheet of Paper / Parchment", "Source Orb", r[1]], category: "Scrolls (Source Orb)" });
  });
  SB.push({ result: "Sheet of Paper", ingredients: ["Wood Pulp", "Oven"], category: "Scrolls (Source Orb)" });
})();

window.RECIPE_NOTES = {
  crafters_kit: "Only available in DOS2:DE with the \u201CCrafter's Kit\u201D mod (Gift Bag #2, \u201CSong of Nature\u201D). Disables achievements.",
  herb_garden: "Only available in DOS2:DE with the \u201CHerb Gardens\u201D mod (Gift Bag #2, \u201CSong of Nature\u201D). Disables achievements."
};
